name: CI

on:
  push:
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5]

    steps:
      - uses: actions/checkout@v4
      - name: Auto green
        if: matrix.instance == 1
        run: |
          git config --local user.email "x074829104@qq.com"
          git config --local user.name "x074829104"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
      - name: Run a multi-line script
        run: |
          sudo apt update && sudo apt install qemu-system-x86 --no-install-recommends
          sudo qemu-system-x86_64 \
            -m 4096M \
            -enable-kvm \
            -cpu host \
            -smp 1 \
            -drive file=os.qcow2,format=qcow2 \
            -boot d \
            -netdev user,id=net0 \
            -device e1000,netdev=net0 \
            -nographic
          
